### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by shma2001gmailcom** [mishashevelinn/cpp_hws#1]
https://github.com/mishashevelinn/cpp_hws/blob/3b6de4979a5c1418a286aa76f668511bc3c3c6eb/Set.cpp#L61

memory leak

**Comment by mishashevelinn** [comment]
Fixed
https://github.com/mishashevelinn/cpp_hws/blob/8e7d203f65163ffa6707d73b5f7fa3f532364c52/Set.cpp#L87-L88

**Comment by shma2001gmailcom** [comment]
fixed
